import requests

username = "aaa"
passwd = "bb"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"


//section[@id='services']//p[contains(text(),'We provide')]
//section[@id='contact']//h2[text()='Contact Us']
//section[@id='contact']//input[@name='name']
//section[@id='contact']//input[@name='email']
//section[@id='contact']//textarea[@name='message']
//section[@id='contact']//button[text()='Send']
//form[@id='login-form']//input[@name='email']
//form[@id='login-form']//input[@name='password']
//form[@id='login-form']//button[text()='Login']
//div[@class='header']//a[@href='/profile']
//div[@class='header']//a[text()='Logout']
//section[@id='features']//h2[text()='Features']
//section[@id='features']//p[contains(text(),'Our platform offers')]
//section[@id='services']//h2[text()='Services']
//button[text()='Login']
//input[@id='login-email']
//input[@id='login-password']
//button[@type='submit' and text()='Login']
//a[@href='/register']
//h1[text()='Welcome to QAuto']
//nav//a[text()='Home']
//nav//a[text()='About']
//nav//a[text()='Contact']
//footer//a[@href='/privacy']
//footer//a[@href='/terms']
//header//img[@alt='QAuto logo']
//header//a[@href='/']
//main//h1[text()='Dashboard']
//main//button[text()='Add new car']
//main//table//th[text()='Car brand']
//main//table//th[text()='Model']
//main//table//th[text()='Year']
//main//table//th[text()='Actions']
//main//table//tr//td[1]
//main//table//tr//td[2]
//main//table//tr//td[3]
//main//table//tr//td[4]//button[text()='Edit']
//main//table//tr//td[4]//button[text()='Delete']
//div[@class='modal']//h3[text()='Add new car']
//div[@class='modal']//input[@name='brand']
//div[@class='modal']//input[@name='model']
//div[@class='modal']//input[@name='year']
//div[@class='modal']//button[text()='Save']
//div[@class='modal']//button[text()='Cancel']
//div[@class='alert']//span[contains(text(),'Error')]
//aside//h2[text()='Navigation']
//aside//a[text()='Home']
//aside//a[text()='Garage']
//aside//a[text()='Settings']
//aside//a[text()='Logout']