import requests

username = "aaa"
passwd = "bb"
url = f"https://{username}:{passwd}@qauto2.forstudy.space"

# Написать 50 XPath или 25 XPath и 25 CSS-локаторов

sign_up_button_xpath_01 = "//button[@class='hero-descriptor_btn btn btn-primary' and text()='Sign up']"
guest_log_in_button_xpath_02 = "//button[@class='header-link -guest' and text()='Guest log in']"
sign_in_button_xpath_03 = "//button[@class='btn btn-outline-white header_signin' and text()='Sign In']"
link_home_xpath_04 = "//a[@class='btn header-link -active' and text()='Home']"
button_about_xpath_05 = "//button[@class='btn header-link' and text()='About']"
button_contacts_xpath_06 = "//button[@class='btn header-link' and text()='Contacts']"
video_xpath_07 = "//div[@class='html5-video-container']/video[@class='video-stream html5-main-video']"
icon_facebook_xpath_08 = "//span[@class='socials_icon icon icon-facebook']"
icon_telegram_xpath_09 = "//span[@class='socials_icon icon icon-telegram']"
icon_youtube_xpath_10 = "//span[@class='socials_icon icon icon-youtube']"
icon_instagram_xpath_11 = "//span[@class='socials_icon icon icon-instagram']"
icon_linkedin_xpath_12 = "//span[@class='socials_icon icon icon-linkedin']"
hillel_school_link_xpath_13 = "//a[@class='contacts_link display-4' and text()='ithillel.ua']"
hillel_support_link_xpath_14 = "//a[@class='contacts_link h4' and text()='support@ithillel.ua']"
footer_logo_xpath_15 = "//a[@class='footer_logo']"
link_garage_header_xpath_16 = "//a[@class='btn header-link -active' and text()='Garage']"
link_fuel_expenses_header_xpath_17 = "//a[@class='btn header-link' and text()='Fuel expenses']"
link_instructions_header_xpath_18 = "//a[@class='btn header-link' and text()='Instructions']"
sidebar_garage_xpath_19 = "//a[@class='btn btn-white btn-sidebar sidebar_btn']/span[@class='icon icon-garage']"
sidebar_fuel_expenses_xpath_20 = "//a[@class='btn btn-white btn-sidebar sidebar_btn']/span[@class='icon icon-fuel']"
sidebar_instructions_xpath_21 = "//a[@class='btn btn-white btn-sidebar sidebar_btn']/span[@class='icon icon-instructions']"
sidebar_logout_xpath_22 = "//a[@class='btn btn-link text-danger btn-sidebar sidebar_btn']"
button_add_car_xpath_23 = "//button[@class='btn btn-primary' and text()='Add car']"
button_my_profile_xpath_24 = "//button[@id='userNavDropdown']"
my_profile_fuel_expenses_xpath_25 = "//div[@class='user-nav show dropdown']/nav[@class='user-nav_menu dropdown-menu show']/a[@class='dropdown-item btn btn-link user-nav_link' and text()='Fuel expenses']"
my_profile_instructions_xpath_26 = "//div[@class='user-nav show dropdown']/nav[@class='user-nav_menu dropdown-menu show']/a[@class='dropdown-item btn btn-link user-nav_link' and text()='Instructions']"
my_profile_garage_xpath_27 = "//div[@class='user-nav show dropdown']/nav[@class='user-nav_menu dropdown-menu show']/a[@class='dropdown-item btn btn-link user-nav_link' and text()='Garage']"
my_profile_logout_xpath_28 = "//div[@class='user-nav show dropdown']/nav[@class='user-nav_menu dropdown-menu show']/button[@class='dropdown-item btn btn-link user-nav_link' and text()='Logout']"
button_add_an_expense_xpath_29 = "//div[@class='item-group']/button[@class='btn btn-primary' and text()='Add an expense']"
button_search_xpath_30 = "//button[@class='instructions-search-controls_search btn btn-primary' and text()='Search']"
dropdown_car_brand_xpath_31 = "//button[@id='brandSelectDropdown']"
dropdown_car_model_xpath_32 = "//button[@id='modelSelectDropdown']"
read_instruction_first_xpath_33 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Front windshield wipers on Audi TT']"
read_instruction_second_xpath_34 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Rear anti roll bar links on Audi TT']"
read_instruction_third_xpath_35 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Rear coil springs on Audi TT']"
read_instruction_fourth_xpath_36 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Rear suspension lower control arm on Audi TT']"
read_instruction_fifth_xpath_37 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Rear suspension strut on Audi TT']"
read_instruction_sixth_xpath_38 = "//a[@class='instruction-link']/p[@class='instruction-link_description' and text()='Spark plugs on Audi TT']"

about_selector_01 = "button.btn.header-link[appscrollto='aboutSection']"
contacts_selector_02 = "button.btn.header-link[appscrollto='contactsSection']"
guest_log_in_selector_03 = "button.header-link.-guest"
sign_in_selector_04 = "button.btn.btn-outline-white.header_signin"
sign_up_selector_05 = "button.hero-descriptor_btn.btn.btn-primary"
icon_facebook_selector_06 = "span.socials_icon.icon.icon-facebook"
icon_telegram_selector_07 = "span.socials_icon.icon.icon-telegram"
icon_youtube_selector_08 = "span.socials_icon.icon.icon-youtube"
icon_linkedin_selector_09 = "span.socials_icon.icon.icon-linkedin"
hillel_school_link_selector_10 = "a.contacts_link.display-4"
hillel_support_selector_11 = "a.contacts_link.h4"
add_car_selector_12 = "button.btn.btn-primary"
